### ISSUE TITLE
jwt.encode fails on force_bytes

### ISSUE THREAD

**Issue by schaefi** [SUSE/mash#122]
I tried to test the pipeline in real life and got a stack trace when the credentials service creates the jwt token:

```
    self.publish_credentials_request(job_id)
  File "/home/ms/Project/mash/mash/services/base_service.py", line 214, in publish_credentials_request
    self.get_credential_request(job_id)
  File "/home/ms/Project/mash/mash/services/base_service.py", line 181, in get_credential_request
    request, self.jwt_secret, algorithm=self.jwt_algorithm
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/jwt/api_jwt.py", line 56, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/jwt/api_jws.py", line 102, in encode
    key = alg_obj.prepare_key(key)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/jwt/algorithms.py", line 140, in prepare_key
    key = force_bytes(key)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/jwt/utils.py", line 30, in force_bytes
    raise TypeError('Expected a string value')
TypeError: Expected a string value
```

The information passed to this code:

```python
token = jwt.encode(
    request, self.jwt_secret, algorithm=self.jwt_algorithm
)
```

is as follows:

```
{'exp': datetime.datetime(2018, 2, 27, 8, 48, 38, 927143), 'iat': datetime.datetime(2018, 2, 27, 8, 43, 38, 927159), 'sub': 'credentials_request', 'aud': 'credentials', 'id': '123', 'iss': 'uploader'}

{'test-aws': {'access_key_id': 123456, 'ssh_key_name': 'key-123', 'ssh_private_key': 'key123', 'secret_access_key': 654321}}

HS256
```

my /etc/mash/mash_config.yaml has this content

```
jwt_algorithm: HS256
jwt_secret:
    test-aws:
        access_key_id: 123456
        secret_access_key: 654321
        ssh_key_name: key-123
        ssh_private_key: key123
log_dir: /var/log/mash/
services:
  - obs
  - uploader
  - testing
  - replication
  - publisher
  - deprecation
  - pint
non_cred_services:
  - obs
obs:
  download_directory: /var/tmp/mash/images
```

**Comment by smarlowucf** [comment]
The secret used by JWT is for signing the token. It must be a string. Which could be a simple string or a public key for example. It is not for holding the credentials values.

**Comment by schaefi** [comment]
the name gave me another impression. jwt_signing_key would imho more clear. Anyway what is an easy procedure to create a stub credentials response as long as the backend does not exist ?

**Comment by smarlowucf** [comment]
The credentials service at the moment is checking for a test key in job doc to pass in credential values for testing.

```
"test_credentials": {
	"access_key_id": "123456",
	"secret_access_key": "654321",
	"ssh_key_name": "my-key",
	"ssh_private_key": "my-key.pem"
}
```

See https://github.com/SUSE/mash/blob/master/mash/services/credentials/service.py#L234.

So to test a job with credentials send a job doc message to credentials service like:

```
{
    "credentials_job": {
        "id": "123",
        "provider": "ec2",
        "provider_accounts": ["test-aws", "test-aws-cn"],
        "requesting_user": "test-aws",
        "last_service": "pint",
        "test_credentials": {
	        "access_key_id": "123456",
	        "secret_access_key": "654321",
	        "ssh_key_name": "my-key",
	        "ssh_private_key": "my-key.pem"
        }
    }
}
```

**Comment by schaefi** [comment]
aha test_credentials that part was missing in messages/credentials_job.json

ok, will give it a try, thanks

**Comment by schaefi** [comment]
ok I used the above job description (just added the missing parts in messages/credentials_job.json) and added it to the examples/run_uploader_jobs.py

now the credentials service ends in the following stack trace when it processed the job

```
(master*)> mash-credentials-service 
ERROR:MashService:Unexpected error:
Traceback (most recent call last):
  File "/home/ms/Project/mash/mash/services/credentials/service.py", line 132, in _handle_job_documents
    job_document = json.loads(message.body)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 205 (char 204)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ms/Project/mash/.tox/3.4/bin/mash-credentials-service", line 11, in <module>
    load_entry_point('mash', 'console_scripts', 'mash-credentials-service')()
  File "/home/ms/Project/mash/mash/services/credentials_service.py", line 36, in main
    host='localhost', service_exchange='credentials',
  File "/home/ms/Project/mash/mash/services/base_service.py", line 101, in __init__
    self.post_init()
  File "/home/ms/Project/mash/mash/services/credentials/service.py", line 43, in post_init
    self.start()
  File "/home/ms/Project/mash/mash/services/credentials/service.py", line 325, in start
    self.channel.start_consuming()
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/channel.py", line 301, in start_consuming
    auto_decode=auto_decode
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/channel.py", line 272, in process_data_events
    self._consumer_callbacks[consumer_tag](message)
  File "/home/ms/Project/mash/mash/services/credentials/service.py", line 146, in _handle_job_documents
    message.ack()
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/message.py", line 113, in ack
    self._channel.basic.ack(delivery_tag=self.delivery_tag)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/basic.py", line 216, in ack
    self._channel.write_frame(ack_frame)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/channel.py", line 330, in write_frame
    self.check_for_errors()
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/channel.py", line 182, in check_for_errors
    raise exception
  File "/home/ms/Project/mash/mash/services/credentials/service.py", line 187, in _notify_invalid_job
    self._publish('jobcreator', 'invalid_job', message)
  File "/home/ms/Project/mash/mash/services/base_service.py", line 231, in _publish
    mandatory=True
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/basic.py", line 194, in publish
    return self._publish_confirm(frames_out)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/basic.py", line 384, in _publish_confirm
    result = self._channel.rpc.get_request(confirm_uuid, raw=True)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/rpc.py", line 98, in get_request
    self._wait_for_request(uuid, adapter or self._default_adapter)
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/rpc.py", line 130, in _wait_for_request
    adapter.check_for_errors()
  File "/home/ms/Project/mash/.tox/3.4/lib/python3.4/site-packages/amqpstorm/channel.py", line 182, in check_for_errors
    raise exception
amqpstorm.exception.AMQPChannelError: Channel 1 was closed by remote server: NOT_FOUND - no exchange 'jobcreator' in vhost '/'
```

jobcreator exchange ?
```

**Comment by schaefi** [comment]
For reference the patch I did

```
diff --git a/examples/messages/credentials_job.json b/examples/messages/credentials_job.json
index e033af8..92b5ada 100644
--- a/examples/messages/credentials_job.json
+++ b/examples/messages/credentials_job.json
@@ -5,5 +5,11 @@
         "provider_accounts": ["test-aws", "test-aws-cn"],
         "requesting_user": "test-aws",
         "last_service": "pint"
+        "test_credentials": {
+               "access_key_id": "123456",
+               "secret_access_key": "654321",
+               "ssh_key_name": "my-key",
+               "ssh_private_key": "my-key.pem"
+        }
     }
 }
diff --git a/examples/run_uploader_jobs.py b/examples/run_uploader_jobs.py
index cadadc2..9d17384 100644
--- a/examples/run_uploader_jobs.py
+++ b/examples/run_uploader_jobs.py
@@ -15,6 +15,7 @@ channel.queue.declare(queue='obs.service', durable=True)
 channel.queue.declare(queue='credentials.service', durable=True)
 
 messages = [
+    ('credentials', 'credentials_job.json'),
     ('obs', 'obs_job_delete.json'),
     ('obs', 'obs_now_job.json'),
     ('uploader', 'uploader_job.json')
```

**Comment by smarlowucf** [comment]
> aha test_credentials that part was missing in messages/credentials_job.json

So the key is only for testing but I suppose it's okay to temporarily change it for testing. Unless we keep it as an option to allow the running of jobs via credentials that are not stored in backend?

> "last_service": "pint"

The comma is missing in the json after last_service.

> jobcreator exchange ?

From one of the previous discussions we decided if an invalid job doc arrives at a service then we will send a notification back to jobcreator since otherwise the job would just be dropped.

So because the job doc is missing a comma it's invalid json and credentials service is trying to send a message to jobcreator but the exchange doesn't exist yet since job creator isn't running. So you can manually create the exchange for testing.

**Comment by schaefi** [comment]
ah yes my fault, sorry, and there is also a log message

```
ERROR 2018-02-27 16:57:26,436 CredentialsService
     Invalid job config file: Expecting ',' delimiter: line 1 column 205 (char 204).
```

:)

**Comment by schaefi** [comment]
btw running mash-job-creator-service says

```
  File "/home/ms/Project/mash/mash/services/jobcreator/service.py", line 41, in post_init
    self.bind_queue(self.service_exchange, 'invalid_config')
TypeError: bind_queue() missing 1 required positional argument: 'name'
```

**Comment by smarlowucf** [comment]
> btw running mash-job-creator-service says

Yeah, I had started the stub for job creator a while back. I think even before we did the two big refactors. But stopped since I decided getting the services in pipeline implemented first was a better workflow. So it's in no way in a usable state. For testing purposes I just manually created a `jobcreator` exchange.

**Comment by schaefi** [comment]
ok got things to work again. btw it's unfortunate that:

+               "access_key_id": "123456",
+               "secret_access_key": "654321",
+               "ssh_key_name": "my-key",
+               "ssh_private_key": "my-key.pem"

does not use the same names as the ec2utils.ec2uploadimg EC2ImageUploader api provides.
Anyway there are some changes in the loop for uploader thus I can take that into account too

**Comment by smarlowucf** [comment]
> does not use the same names as the ec2utils.ec2uploadimg EC2ImageUploader api provides

Can be fixed. For replication, testing and publisher boto3 is directly used. So matching those names would also be nice. I originally dropper the `aws_` from names. But would be nice to match and be descriptive.

However, ec2utils does not match boto3 either :confused: .
